// utils/pdfExport.js
// Generates a downloadable PDF (notes / summary / quiz) using PDFKit
// and streams it directly to the HTTP response.

const PDFDocument = require('pdfkit');

/**
 * Streams a simple, well-formatted PDF to the response.
 * @param {import('express').Response} res
 * @param {string} title
 * @param {string} bodyText
 */
const streamTextAsPDF = (res, title, bodyText) => {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${title.replace(/\s+/g, '_')}.pdf"`);

  doc.pipe(res);

  doc.fontSize(20).fillColor('#4f46e5').text(title, { align: 'center' });
  doc.moveDown();
  doc.fontSize(10).fillColor('#6b7280').text(`Generated by AI Student Assistant • ${new Date().toLocaleString()}`, {
    align: 'center',
  });
  doc.moveDown(2);
  doc.fontSize(12).fillColor('#111827').text(bodyText, { align: 'left', lineGap: 4 });

  doc.end();
};

module.exports = { streamTextAsPDF };
