// models/Flashcard.js
// A flashcard "deck" generated by AI from notes or a topic, with front/back cards.

const mongoose = require('mongoose');

const cardSchema = new mongoose.Schema(
  {
    front: { type: String, required: true },
    back: { type: String, required: true },
  },
  { _id: false }
);

const flashcardDeckSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    note: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Note',
      default: null,
    },
    title: {
      type: String,
      required: true,
    },
    cards: {
      type: [cardSchema],
      default: [],
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('FlashcardDeck', flashcardDeckSchema);
